import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '介绍',
    },
    {
      type: 'category',
      label: '前端开发',
      items: [
        '前端/前端基础--寒枫',
        '前端/CommonJS与ES模块',
        '前端/HTML+CSS+JS—寒枫',
        '前端/Typescript',
        '前端/React基础--寒枫',
        '前端/Vue基础--寒枫',
        '前端/Next.js基础',
        '前端/Node.js基础--寒枫',
        '前端/JavaScript 构建工具',
        '前端/包管理工具',
        '前端/浏览器原理--寒枫',
        '前端/浏览器扩展与脚本--寒枫',
        '前端/网页脚本',
        '前端/网页2D与3D',
        '前端/小程序与Uniapp开发--寒枫',
        '前端/Flutter',
        '前端/安卓应用开发--寒枫',
        '前端/Qt基础--寒枫',
      ],
    },
    {
      type: 'category',
      label: '后端开发',
      items: [
        '后端/后端基础--寒枫',
        '后端/分布式',
        '后端/微服务架构—寒枫',
        '后端/云原生',
        '后端/ClickHouse基础',
        '后端/Django基础--寒枫',
        '后端/Docker基础教程--寒枫',
        '后端/FastAPI基础',
        '后端/Flask基础--寒枫',
        '后端/Java基础—寒枫',
        '后端/Maven基础',
        '后端/Nginx基础--寒枫',
        '后端/Php基础--寒枫',
        '后端/PostgreSQL基础',
        '后端/Redis基础',
        '后端/Server-Sent Events（SSE）',
        '后端/Spring开发基础--寒枫',
        '后端/SQL速记--寒枫',
        '后端/Websocket与WebRTC',
      ],
    },
    {
      type: 'category',
      label: '机器学习',
      items: [
        '机器学习/机器学习入门',
        '机器学习/CNN神经网络',
        '机器学习/RNN神经网络',
        '机器学习/计算机视觉--寒枫',
        '机器学习/具身智能',
        '机器学习/你必须要了解的Transformer',
        '机器学习/深度学习论文阅读--寒枫',
        '机器学习/数据处理',
        '机器学习/吴恩达ML学习笔记--寒枫25年11月',
        '机器学习/Embedding模型',
        '机器学习/多模态大模型--寒枫',
        '机器学习/动手学深度学习笔记',
        '机器学习/Pytorch',
        '机器学习/LangChain入门--寒枫',
        '机器学习/Rerank模型',
        '机器学习/LLM微调理论知识—寒枫',
        '机器学习/大模型实战入门--寒枫',
        '机器学习/HappyLLM笔记--寒枫',
      ],
    },
    {
      type: 'category',
      label: '读书笔记',
      items: [
        '读书笔记/蛊真人--方源历程',
        '读书笔记/蛊真人--世界观设定',
        '读书笔记/诡秘之主',
      ],
    },
    {
      type: 'category',
      label: '嵌入式开发',
      items: [
        '嵌入式/Keli与μVision使用教程--寒枫',
        '嵌入式/汇编语言学习--寒枫',
        '嵌入式/数电设计--寒枫',
        '嵌入式/ARM处理器--寒枫25年6月',
        '嵌入式/STM32学习笔记--寒枫24年9月',
        '嵌入式/嵌入式操作系统-寒枫25年5月',
        '嵌入式/ROS2基础--寒枫',
      ],
    },
  ],
};

export default sidebars;
