import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // 使用自动生成的侧边栏
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
